version: "3.8"
services:
    db:
        image: postgres:14.1-alpine
        env_file:
            - ./server/.env
        ports:
            - "5432:5432"
        volumes:
            - db:/var/lib/postgresql/data
        networks:
            - app
    backend:
        depends_on:
            - db
        build: ./server
        env_file:
            - ./server/.env
        ports:
            - "3000:3000"
        networks:
            - app
        extra_hosts:
            - host.docker.internal:host-gateway
    frontend:
        build: ./frontend
        env_file:
            - ./frontend/.env
        ports:
            - "8000:8000"
        networks:
            - app
        extra_hosts:
            - host.docker.internal:host-gateway
volumes:
    db:
        driver: local
    pgadmin-data:
networks:
    app:
        driver: bridge
